@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1.3 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Mon Feb 01 16:26:30 +0100 2021
REM SW Build 2644227 on Wed Sep  4 09:45:24 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto b58e5888be0b425eba615d97a8f7fed4 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot DCM_ctrl_TB_behav xil_defaultlib.DCM_ctrl_TB -log elaborate.log"
call xelab  -wto b58e5888be0b425eba615d97a8f7fed4 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot DCM_ctrl_TB_behav xil_defaultlib.DCM_ctrl_TB -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
