@echo off
REM ****************************************************************************
REM Vivado (TM) v2018.3_AR72013 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Tue Apr 14 11:48:01 +0200 2020
REM SW Build 2405991 on Thu Dec  6 23:38:27 MST 2018
REM
REM Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
call xelab  -wto 87c6d035be1e436a85b94a5ab00971d6 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot SOL_ctrl_TB_behav xil_defaultlib.SOL_ctrl_TB -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
