@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1.3 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Thu May 14 15:30:39 +0200 2020
REM SW Build 2644227 on Wed Sep  4 09:45:24 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim SM_ctrl_TB_behav -key {Behavioral:sim_1:Functional:SM_ctrl_TB} -tclbatch SM_ctrl_TB.tcl -view D:/MW/RTT/VVD/ZED/P0/repo/SM_ctrl/SM_ctrl_TB_behav.wcfg -log simulate.log"
call xsim  SM_ctrl_TB_behav -key {Behavioral:sim_1:Functional:SM_ctrl_TB} -tclbatch SM_ctrl_TB.tcl -view D:/MW/RTT/VVD/ZED/P0/repo/SM_ctrl/SM_ctrl_TB_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
