# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7s100fgga676-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/MW/RTT/VVD/S/S_7/S7/S7.cache/wt [current_project]
set_property parent.project_path D:/MW/RTT/VVD/S/S_7/S7/S7.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_repo_paths d:/MW/RTT/VVD/S/S_7/repo [current_project]
update_ip_catalog
set_property ip_output_repo d:/MW/RTT/VVD/S/S_7/S7/S7.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib D:/MW/RTT/VVD/S/S_7/S7/S7.srcs/sources_1/bd/S7/hdl/S7_wrapper.vhd
add_files D:/MW/RTT/VVD/S/S_7/S7/S7.srcs/sources_1/bd/S7/S7.bd
set_property used_in_implementation false [get_files -all d:/MW/RTT/VVD/S/S_7/S7/S7.srcs/sources_1/bd/S7/ip/S7_SM_ctrl_0_0/SM_ctrl.srcs/constrs_1/new/SM_ctrl_tests.xdc]
set_property used_in_implementation false [get_files -all d:/MW/RTT/VVD/S/S_7/S7/S7.srcs/sources_1/bd/S7/ip/S7_SM_ctrl_1_0/SM_ctrl.srcs/constrs_1/new/SM_ctrl_tests.xdc]
set_property used_in_implementation false [get_files -all d:/MW/RTT/VVD/S/S_7/S7/S7.srcs/sources_1/bd/S7/ip/S7_SM_ctrl_2_0/SM_ctrl.srcs/constrs_1/new/SM_ctrl_tests.xdc]
set_property used_in_implementation false [get_files -all d:/MW/RTT/VVD/S/S_7/S7/S7.srcs/sources_1/bd/S7/ip/S7_SM_ctrl_3_0/SM_ctrl.srcs/constrs_1/new/SM_ctrl_tests.xdc]
set_property used_in_implementation false [get_files -all d:/MW/RTT/VVD/S/S_7/S7/S7.srcs/sources_1/bd/S7/ip/S7_SM_ctrl_4_0/SM_ctrl.srcs/constrs_1/new/SM_ctrl_tests.xdc]
set_property used_in_implementation false [get_files -all d:/MW/RTT/VVD/S/S_7/S7/S7.srcs/sources_1/bd/S7/ip/S7_SM_ctrl_5_0/SM_ctrl.srcs/constrs_1/new/SM_ctrl_tests.xdc]
set_property used_in_implementation false [get_files -all d:/MW/RTT/VVD/S/S_7/S7/S7.srcs/sources_1/bd/S7/ip/S7_SM_ctrl_6_0/SM_ctrl.srcs/constrs_1/new/SM_ctrl_tests.xdc]
set_property used_in_implementation false [get_files -all d:/MW/RTT/VVD/S/S_7/S7/S7.srcs/sources_1/bd/S7/ip/S7_SM_ctrl_7_0/SM_ctrl.srcs/constrs_1/new/SM_ctrl_tests.xdc]
set_property used_in_implementation false [get_files -all d:/MW/RTT/VVD/S/S_7/S7/S7.srcs/sources_1/bd/S7/ip/S7_SM_ctrl_8_0/SM_ctrl.srcs/constrs_1/new/SM_ctrl_tests.xdc]
set_property used_in_implementation false [get_files -all d:/MW/RTT/VVD/S/S_7/S7/S7.srcs/sources_1/bd/S7/ip/S7_SM_ctrl_9_0/SM_ctrl.srcs/constrs_1/new/SM_ctrl_tests.xdc]
set_property used_in_implementation false [get_files -all d:/MW/RTT/VVD/S/S_7/S7/S7.srcs/sources_1/bd/S7/ip/S7_SM_ctrl_10_0/SM_ctrl.srcs/constrs_1/new/SM_ctrl_tests.xdc]
set_property used_in_implementation false [get_files -all d:/MW/RTT/VVD/S/S_7/S7/S7.srcs/sources_1/bd/S7/ip/S7_SM_ctrl_11_0/SM_ctrl.srcs/constrs_1/new/SM_ctrl_tests.xdc]
set_property used_in_implementation false [get_files -all d:/MW/RTT/VVD/S/S_7/S7/S7.srcs/sources_1/bd/S7/ip/S7_SM_ctrl_12_0/SM_ctrl.srcs/constrs_1/new/SM_ctrl_tests.xdc]
set_property used_in_implementation false [get_files -all d:/MW/RTT/VVD/S/S_7/S7/S7.srcs/sources_1/bd/S7/ip/S7_SM_ctrl_13_0/SM_ctrl.srcs/constrs_1/new/SM_ctrl_tests.xdc]
set_property used_in_implementation false [get_files -all d:/MW/RTT/VVD/S/S_7/S7/S7.srcs/sources_1/bd/S7/ip/S7_SM_ctrl_14_0/SM_ctrl.srcs/constrs_1/new/SM_ctrl_tests.xdc]
set_property used_in_implementation false [get_files -all d:/MW/RTT/VVD/S/S_7/S7/S7.srcs/sources_1/bd/S7/ip/S7_SM_ctrl_15_0/SM_ctrl.srcs/constrs_1/new/SM_ctrl_tests.xdc]
set_property used_in_implementation false [get_files -all d:/MW/RTT/VVD/S/S_7/S7/S7.srcs/sources_1/bd/S7/ip/S7_SM_ctrl_16_0/SM_ctrl.srcs/constrs_1/new/SM_ctrl_tests.xdc]
set_property used_in_implementation false [get_files -all d:/MW/RTT/VVD/S/S_7/S7/S7.srcs/sources_1/bd/S7/ip/S7_SM_ctrl_17_0/SM_ctrl.srcs/constrs_1/new/SM_ctrl_tests.xdc]
set_property used_in_implementation false [get_files -all d:/MW/RTT/VVD/S/S_7/S7/S7.srcs/sources_1/bd/S7/ip/S7_SM_ctrl_18_0/SM_ctrl.srcs/constrs_1/new/SM_ctrl_tests.xdc]
set_property used_in_implementation false [get_files -all d:/MW/RTT/VVD/S/S_7/S7/S7.srcs/sources_1/bd/S7/ip/S7_SM_ctrl_19_0/SM_ctrl.srcs/constrs_1/new/SM_ctrl_tests.xdc]
set_property used_in_implementation false [get_files -all d:/MW/RTT/VVD/S/S_7/S7/S7.srcs/sources_1/bd/S7/ip/S7_axi_gpio_0_0/S7_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/MW/RTT/VVD/S/S_7/S7/S7.srcs/sources_1/bd/S7/ip/S7_axi_gpio_0_0/S7_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/MW/RTT/VVD/S/S_7/S7/S7.srcs/sources_1/bd/S7/ip/S7_axi_gpio_0_0/S7_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/MW/RTT/VVD/S/S_7/S7/S7.srcs/sources_1/bd/S7/ip/S7_axi_uartlite_0_0/S7_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/MW/RTT/VVD/S/S_7/S7/S7.srcs/sources_1/bd/S7/ip/S7_axi_uartlite_0_0/S7_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/MW/RTT/VVD/S/S_7/S7/S7.srcs/sources_1/bd/S7/ip/S7_axi_uartlite_0_0/S7_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/MW/RTT/VVD/S/S_7/S7/S7.srcs/sources_1/bd/S7/ip/S7_clk_wiz_1_0/S7_clk_wiz_1_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/MW/RTT/VVD/S/S_7/S7/S7.srcs/sources_1/bd/S7/ip/S7_clk_wiz_1_0/S7_clk_wiz_1_0.xdc]
set_property used_in_implementation false [get_files -all d:/MW/RTT/VVD/S/S_7/S7/S7.srcs/sources_1/bd/S7/ip/S7_clk_wiz_1_0/S7_clk_wiz_1_0_late.xdc]
set_property used_in_implementation false [get_files -all d:/MW/RTT/VVD/S/S_7/S7/S7.srcs/sources_1/bd/S7/ip/S7_clk_wiz_1_0/S7_clk_wiz_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/MW/RTT/VVD/S/S_7/S7/S7.srcs/sources_1/bd/S7/ip/S7_rst_clk_wiz_1_100M_0/S7_rst_clk_wiz_1_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/MW/RTT/VVD/S/S_7/S7/S7.srcs/sources_1/bd/S7/ip/S7_rst_clk_wiz_1_100M_0/S7_rst_clk_wiz_1_100M_0.xdc]
set_property used_in_implementation false [get_files -all d:/MW/RTT/VVD/S/S_7/S7/S7.srcs/sources_1/bd/S7/ip/S7_rst_clk_wiz_1_100M_0/S7_rst_clk_wiz_1_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/MW/RTT/VVD/S/S_7/S7/S7.srcs/sources_1/bd/S7/ip/S7_axi_chip2chip_0_0/S7_axi_chip2chip_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/MW/RTT/VVD/S/S_7/S7/S7.srcs/sources_1/bd/S7/ip/S7_axi_chip2chip_0_0/S7_axi_chip2chip_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/MW/RTT/VVD/S/S_7/S7/S7.srcs/sources_1/bd/S7/ip/S7_axi_chip2chip_0_0/S7_axi_chip2chip_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/MW/RTT/VVD/S/S_7/S7/S7.srcs/sources_1/bd/S7/ip/S7_util_ds_buf_0_0/S7_util_ds_buf_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/MW/RTT/VVD/S/S_7/S7/S7.srcs/sources_1/bd/S7/ip/S7_util_ds_buf_0_0/S7_util_ds_buf_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/MW/RTT/VVD/S/S_7/S7/S7.srcs/sources_1/bd/S7/ip/S7_util_ds_buf_0_1/S7_util_ds_buf_0_1_board.xdc]
set_property used_in_implementation false [get_files -all d:/MW/RTT/VVD/S/S_7/S7/S7.srcs/sources_1/bd/S7/ip/S7_util_ds_buf_0_1/S7_util_ds_buf_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/MW/RTT/VVD/S/S_7/S7/S7.srcs/sources_1/bd/S7/ip/S7_xbar_2/S7_xbar_2_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/MW/RTT/VVD/S/S_7/S7/S7.srcs/sources_1/bd/S7/ip/S7_SM_alg_server_0_0/SM_alg_server.srcs/sources_1/ip/SM_req_fifo/SM_req_fifo.xdc]
set_property used_in_implementation false [get_files -all d:/MW/RTT/VVD/S/S_7/S7/S7.srcs/sources_1/bd/S7/ip/S7_SM_alg_server_0_0/SM_alg_server.srcs/sources_1/ip/SM_status_fifo/SM_status_fifo.xdc]
set_property used_in_implementation false [get_files -all d:/MW/RTT/VVD/S/S_7/S7/S7.srcs/sources_1/bd/S7/ip/S7_SM_alg_server_1_1_1/SM_alg_server.srcs/sources_1/ip/SM_req_fifo/SM_req_fifo.xdc]
set_property used_in_implementation false [get_files -all d:/MW/RTT/VVD/S/S_7/S7/S7.srcs/sources_1/bd/S7/ip/S7_SM_alg_server_1_1_1/SM_alg_server.srcs/sources_1/ip/SM_status_fifo/SM_status_fifo.xdc]
set_property used_in_implementation false [get_files -all d:/MW/RTT/VVD/S/S_7/S7/S7.srcs/sources_1/bd/S7/ip/S7_axi_dma_0_0/S7_axi_dma_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/MW/RTT/VVD/S/S_7/S7/S7.srcs/sources_1/bd/S7/ip/S7_axi_dma_0_0/S7_axi_dma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/MW/RTT/VVD/S/S_7/S7/S7.srcs/sources_1/bd/S7/ip/S7_axi_dma_0_0/S7_axi_dma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/MW/RTT/VVD/S/S_7/S7/S7.srcs/sources_1/bd/S7/ip/S7_xbar_3/S7_xbar_3_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/MW/RTT/VVD/S/S_7/S7/S7.srcs/sources_1/bd/S7/ip/S7_axis_data_fifo_0_0/S7_axis_data_fifo_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/MW/RTT/VVD/S/S_7/S7/S7.srcs/sources_1/bd/S7/ip/S7_axis_data_fifo_0_1/S7_axis_data_fifo_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/MW/RTT/VVD/S/S_7/S7/S7.srcs/sources_1/bd/S7/ip/S7_m00_data_fifo_0/S7_m00_data_fifo_0_ooc.xdc]
set_property used_in_implementation false [get_files -all D:/MW/RTT/VVD/S/S_7/S7/S7.srcs/sources_1/bd/S7/S7_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/MW/RTT/VVD/S/S_7/S7/S7.srcs/constrs_1/new/S7_IOs.xdc
set_property used_in_implementation false [get_files D:/MW/RTT/VVD/S/S_7/S7/S7.srcs/constrs_1/new/S7_IOs.xdc]

read_xdc D:/MW/RTT/VVD/S/S_7/S7/S7.srcs/constrs_1/new/S7_Timing.xdc
set_property used_in_implementation false [get_files D:/MW/RTT/VVD/S/S_7/S7/S7.srcs/constrs_1/new/S7_Timing.xdc]

read_xdc D:/MW/RTT/VVD/S/S_7/S7/S7.srcs/constrs_1/new/S7_bitstream.xdc
set_property used_in_implementation false [get_files D:/MW/RTT/VVD/S/S_7/S7/S7.srcs/constrs_1/new/S7_bitstream.xdc]

read_xdc D:/MW/RTT/VVD/S/S_7/S7/S7.srcs/constrs_1/new/S7_Debug.xdc
set_property used_in_implementation false [get_files D:/MW/RTT/VVD/S/S_7/S7/S7.srcs/constrs_1/new/S7_Debug.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top S7_wrapper -part xc7s100fgga676-1 -keep_equivalent_registers -no_lc


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef S7_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file S7_wrapper_utilization_synth.rpt -pb S7_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
