# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/MW/RTT/VVD/S/S_7-Pastrocchi/S_7/S7/S7.srcs/sources_1/bd/S7/ip/S7_xbar_3/S7_xbar_3.xci
# IP: The module: 'S7_xbar_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/MW/RTT/VVD/S/S_7-Pastrocchi/S_7/S7/S7.srcs/sources_1/bd/S7/ip/S7_xbar_3/S7_xbar_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'S7_xbar_3'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: D:/MW/RTT/VVD/S/S_7-Pastrocchi/S_7/S7/S7.srcs/sources_1/bd/S7/ip/S7_xbar_3/S7_xbar_3.xci
# IP: The module: 'S7_xbar_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/MW/RTT/VVD/S/S_7-Pastrocchi/S_7/S7/S7.srcs/sources_1/bd/S7/ip/S7_xbar_3/S7_xbar_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'S7_xbar_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
