webtalk_init -webtalk_dir D:/MW/RTT/VVD/S/S_3/repo/DCM_ctrl/DCM_ctrl.sim/sim_1/behav/xsim/xsim.dir/DCM_ctrl_TB_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Feb  1 16:28:49 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2644227" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "d319dd8d-f7d8-4846-9726-59658645eba0" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "b58e5888be0b425eba615d97a8f7fed4" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2208 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "2 ms" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "3" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.72_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "14160_KB" -context "xsim\\usage"
webtalk_transmit -clientid 845380902 -regid "" -xml D:/MW/RTT/VVD/S/S_3/repo/DCM_ctrl/DCM_ctrl.sim/sim_1/behav/xsim/xsim.dir/DCM_ctrl_TB_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/MW/RTT/VVD/S/S_3/repo/DCM_ctrl/DCM_ctrl.sim/sim_1/behav/xsim/xsim.dir/DCM_ctrl_TB_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/MW/RTT/VVD/S/S_3/repo/DCM_ctrl/DCM_ctrl.sim/sim_1/behav/xsim/xsim.dir/DCM_ctrl_TB_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
