# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/MW/RTT/VVD/ZED/P0/repo/SM_alg_server/SM_alg_server.srcs/sources_1/ip/div_s50_s36_lat34/div_s50_s36_lat34.xci
# IP: The module: 'div_s50_s36_lat34' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/MW/RTT/VVD/ZED/P0/repo/SM_alg_server/SM_alg_server.srcs/sources_1/ip/div_s50_s36_lat34/div_s50_s36_lat34_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'div_s50_s36_lat34'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/MW/RTT/VVD/ZED/P0/repo/SM_alg_server/SM_alg_server.srcs/sources_1/ip/div_s50_s36_lat34/div_s50_s36_lat34.xci
# IP: The module: 'div_s50_s36_lat34' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/MW/RTT/VVD/ZED/P0/repo/SM_alg_server/SM_alg_server.srcs/sources_1/ip/div_s50_s36_lat34/div_s50_s36_lat34_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'div_s50_s36_lat34'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
