# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/MW/RTT/VVD/S/S_3/repo/SM_alg_server/SM_alg_server.srcs/sources_1/ip/SM_status_fifo/SM_status_fifo.xci
# IP: The module: 'SM_status_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/MW/RTT/VVD/S/S_3/repo/SM_alg_server/SM_alg_server.srcs/sources_1/ip/SM_status_fifo/SM_status_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'SM_status_fifo'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/MW/RTT/VVD/S/S_3/repo/SM_alg_server/SM_alg_server.srcs/sources_1/ip/SM_status_fifo/SM_status_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'SM_status_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/MW/RTT/VVD/S/S_3/repo/SM_alg_server/SM_alg_server.srcs/sources_1/ip/SM_status_fifo/SM_status_fifo.xci
# IP: The module: 'SM_status_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/MW/RTT/VVD/S/S_3/repo/SM_alg_server/SM_alg_server.srcs/sources_1/ip/SM_status_fifo/SM_status_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'SM_status_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/MW/RTT/VVD/S/S_3/repo/SM_alg_server/SM_alg_server.srcs/sources_1/ip/SM_status_fifo/SM_status_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'SM_status_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
