
 PARAMETER VERSION = 2.2.0


BEGIN OS
 PARAMETER OS_NAME = standalone
 PARAMETER OS_VER = 7.0
 PARAMETER PROC_INSTANCE = microblaze_0
 PARAMETER stdin = axi_uartlite_0
 PARAMETER stdout = axi_uartlite_0
END


BEGIN PROCESSOR
 PARAMETER DRIVER_NAME = cpu
 PARAMETER DRIVER_VER = 2.9
 PARAMETER HW_INSTANCE = microblaze_0
 PARAMETER compiler_flags =  -mlittle-endian -mxl-barrel-shift -mno-xl-soft-mul -mxl-multiply-high -mhard-float -mxl-float-convert -mxl-float-sqrt -mcpu=v11.0
END


BEGIN DRIVER
 PARAMETER DRIVER_NAME = DCM_regs
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = DCM_5_DCM_regs_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = PHS_regs
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = PHS_50_PHS_regs_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = SM_regs
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = SM_20_SM_regs_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = SOL_regs
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = SOL_10_SOL_regs_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = axidma
 PARAMETER DRIVER_VER = 9.9
 PARAMETER HW_INSTANCE = axi_dma_1
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = gpio
 PARAMETER DRIVER_VER = 4.4
 PARAMETER HW_INSTANCE = axi_gpio_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = uartlite
 PARAMETER DRIVER_VER = 3.2
 PARAMETER HW_INSTANCE = axi_uartlite_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = bram
 PARAMETER DRIVER_VER = 4.3
 PARAMETER HW_INSTANCE = microblaze_0_local_memory_dlmb_bram_if_cntlr
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = bram
 PARAMETER DRIVER_VER = 4.3
 PARAMETER HW_INSTANCE = microblaze_0_local_memory_ilmb_bram_if_cntlr
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.0
 PARAMETER HW_INSTANCE = axi_c2c_s
END


