# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/MW/RTT/VVD/S/S_4/sim_DDR/sim_DDR.srcs/sources_1/ip/mmcm_z/mmcm_z.xci
# IP: The module: 'mmcm_z' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/MW/RTT/VVD/S/S_4/sim_DDR/sim_DDR.srcs/sources_1/ip/mmcm_z/mmcm_z_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm_z'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/MW/RTT/VVD/S/S_4/sim_DDR/sim_DDR.srcs/sources_1/ip/mmcm_z/mmcm_z.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm_z'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/MW/RTT/VVD/S/S_4/sim_DDR/sim_DDR.srcs/sources_1/ip/mmcm_z/mmcm_z_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm_z'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/MW/RTT/VVD/S/S_4/sim_DDR/sim_DDR.srcs/sources_1/ip/mmcm_z/mmcm_z_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm_z'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/MW/RTT/VVD/S/S_4/sim_DDR/sim_DDR.srcs/sources_1/ip/mmcm_z/mmcm_z.xci
# IP: The module: 'mmcm_z' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/MW/RTT/VVD/S/S_4/sim_DDR/sim_DDR.srcs/sources_1/ip/mmcm_z/mmcm_z_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm_z'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/MW/RTT/VVD/S/S_4/sim_DDR/sim_DDR.srcs/sources_1/ip/mmcm_z/mmcm_z.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm_z'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/MW/RTT/VVD/S/S_4/sim_DDR/sim_DDR.srcs/sources_1/ip/mmcm_z/mmcm_z_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm_z'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/MW/RTT/VVD/S/S_4/sim_DDR/sim_DDR.srcs/sources_1/ip/mmcm_z/mmcm_z_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm_z'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
