# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/S7_IOs.xdc

# XDC: new/S7_Timing.xdc

# Block Designs: bd/S7/S7.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7 || ORIG_REF_NAME==S7} -quiet] -quiet

# IP: bd/S7/ip/S7_DCM_ctrl_0_0/S7_DCM_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_DCM_ctrl_0_0 || ORIG_REF_NAME==S7_DCM_ctrl_0_0} -quiet] -quiet

# IP: bd/S7/ip/S7_DCM_ctrl_1_0/S7_DCM_ctrl_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_DCM_ctrl_1_0 || ORIG_REF_NAME==S7_DCM_ctrl_1_0} -quiet] -quiet

# IP: bd/S7/ip/S7_DCM_ctrl_2_0/S7_DCM_ctrl_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_DCM_ctrl_2_0 || ORIG_REF_NAME==S7_DCM_ctrl_2_0} -quiet] -quiet

# IP: bd/S7/ip/S7_DCM_ctrl_3_0/S7_DCM_ctrl_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_DCM_ctrl_3_0 || ORIG_REF_NAME==S7_DCM_ctrl_3_0} -quiet] -quiet

# IP: bd/S7/ip/S7_DCM_ctrl_4_0/S7_DCM_ctrl_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_DCM_ctrl_4_0 || ORIG_REF_NAME==S7_DCM_ctrl_4_0} -quiet] -quiet

# IP: bd/S7/ip/S7_DCM_regs_0_0/S7_DCM_regs_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_DCM_regs_0_0 || ORIG_REF_NAME==S7_DCM_regs_0_0} -quiet] -quiet

# IP: bd/S7/ip/S7_PHS_ctrl_0_0/S7_PHS_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_PHS_ctrl_0_0 || ORIG_REF_NAME==S7_PHS_ctrl_0_0} -quiet] -quiet

# IP: bd/S7/ip/S7_PHS_ctrl_1_0/S7_PHS_ctrl_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_PHS_ctrl_1_0 || ORIG_REF_NAME==S7_PHS_ctrl_1_0} -quiet] -quiet

# IP: bd/S7/ip/S7_PHS_ctrl_2_0/S7_PHS_ctrl_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_PHS_ctrl_2_0 || ORIG_REF_NAME==S7_PHS_ctrl_2_0} -quiet] -quiet

# IP: bd/S7/ip/S7_PHS_ctrl_3_0/S7_PHS_ctrl_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_PHS_ctrl_3_0 || ORIG_REF_NAME==S7_PHS_ctrl_3_0} -quiet] -quiet

# IP: bd/S7/ip/S7_PHS_ctrl_4_0/S7_PHS_ctrl_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_PHS_ctrl_4_0 || ORIG_REF_NAME==S7_PHS_ctrl_4_0} -quiet] -quiet

# IP: bd/S7/ip/S7_PHS_ctrl_5_0/S7_PHS_ctrl_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_PHS_ctrl_5_0 || ORIG_REF_NAME==S7_PHS_ctrl_5_0} -quiet] -quiet

# IP: bd/S7/ip/S7_PHS_ctrl_6_0/S7_PHS_ctrl_6_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_PHS_ctrl_6_0 || ORIG_REF_NAME==S7_PHS_ctrl_6_0} -quiet] -quiet

# IP: bd/S7/ip/S7_PHS_ctrl_7_0/S7_PHS_ctrl_7_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_PHS_ctrl_7_0 || ORIG_REF_NAME==S7_PHS_ctrl_7_0} -quiet] -quiet

# IP: bd/S7/ip/S7_PHS_ctrl_8_0/S7_PHS_ctrl_8_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_PHS_ctrl_8_0 || ORIG_REF_NAME==S7_PHS_ctrl_8_0} -quiet] -quiet

# IP: bd/S7/ip/S7_PHS_ctrl_9_0/S7_PHS_ctrl_9_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_PHS_ctrl_9_0 || ORIG_REF_NAME==S7_PHS_ctrl_9_0} -quiet] -quiet

# IP: bd/S7/ip/S7_PHS_ctrl_10_0/S7_PHS_ctrl_10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_PHS_ctrl_10_0 || ORIG_REF_NAME==S7_PHS_ctrl_10_0} -quiet] -quiet

# IP: bd/S7/ip/S7_PHS_ctrl_11_0/S7_PHS_ctrl_11_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_PHS_ctrl_11_0 || ORIG_REF_NAME==S7_PHS_ctrl_11_0} -quiet] -quiet

# IP: bd/S7/ip/S7_PHS_ctrl_12_0/S7_PHS_ctrl_12_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_PHS_ctrl_12_0 || ORIG_REF_NAME==S7_PHS_ctrl_12_0} -quiet] -quiet

# IP: bd/S7/ip/S7_PHS_ctrl_13_0/S7_PHS_ctrl_13_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_PHS_ctrl_13_0 || ORIG_REF_NAME==S7_PHS_ctrl_13_0} -quiet] -quiet

# IP: bd/S7/ip/S7_PHS_ctrl_14_0/S7_PHS_ctrl_14_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_PHS_ctrl_14_0 || ORIG_REF_NAME==S7_PHS_ctrl_14_0} -quiet] -quiet

# IP: bd/S7/ip/S7_PHS_ctrl_15_0/S7_PHS_ctrl_15_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_PHS_ctrl_15_0 || ORIG_REF_NAME==S7_PHS_ctrl_15_0} -quiet] -quiet

# IP: bd/S7/ip/S7_PHS_ctrl_16_0/S7_PHS_ctrl_16_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_PHS_ctrl_16_0 || ORIG_REF_NAME==S7_PHS_ctrl_16_0} -quiet] -quiet

# IP: bd/S7/ip/S7_PHS_ctrl_17_0/S7_PHS_ctrl_17_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_PHS_ctrl_17_0 || ORIG_REF_NAME==S7_PHS_ctrl_17_0} -quiet] -quiet

# IP: bd/S7/ip/S7_PHS_ctrl_18_0/S7_PHS_ctrl_18_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_PHS_ctrl_18_0 || ORIG_REF_NAME==S7_PHS_ctrl_18_0} -quiet] -quiet

# IP: bd/S7/ip/S7_PHS_ctrl_19_0/S7_PHS_ctrl_19_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_PHS_ctrl_19_0 || ORIG_REF_NAME==S7_PHS_ctrl_19_0} -quiet] -quiet

# IP: bd/S7/ip/S7_PHS_ctrl_20_0/S7_PHS_ctrl_20_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_PHS_ctrl_20_0 || ORIG_REF_NAME==S7_PHS_ctrl_20_0} -quiet] -quiet

# IP: bd/S7/ip/S7_PHS_ctrl_21_0/S7_PHS_ctrl_21_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_PHS_ctrl_21_0 || ORIG_REF_NAME==S7_PHS_ctrl_21_0} -quiet] -quiet

# IP: bd/S7/ip/S7_PHS_ctrl_22_0/S7_PHS_ctrl_22_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_PHS_ctrl_22_0 || ORIG_REF_NAME==S7_PHS_ctrl_22_0} -quiet] -quiet

# IP: bd/S7/ip/S7_PHS_ctrl_23_0/S7_PHS_ctrl_23_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_PHS_ctrl_23_0 || ORIG_REF_NAME==S7_PHS_ctrl_23_0} -quiet] -quiet

# IP: bd/S7/ip/S7_PHS_ctrl_24_0/S7_PHS_ctrl_24_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_PHS_ctrl_24_0 || ORIG_REF_NAME==S7_PHS_ctrl_24_0} -quiet] -quiet

# IP: bd/S7/ip/S7_PHS_ctrl_25_0/S7_PHS_ctrl_25_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_PHS_ctrl_25_0 || ORIG_REF_NAME==S7_PHS_ctrl_25_0} -quiet] -quiet

# IP: bd/S7/ip/S7_PHS_ctrl_26_0/S7_PHS_ctrl_26_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_PHS_ctrl_26_0 || ORIG_REF_NAME==S7_PHS_ctrl_26_0} -quiet] -quiet

# IP: bd/S7/ip/S7_PHS_ctrl_27_0/S7_PHS_ctrl_27_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_PHS_ctrl_27_0 || ORIG_REF_NAME==S7_PHS_ctrl_27_0} -quiet] -quiet

# IP: bd/S7/ip/S7_PHS_ctrl_28_0/S7_PHS_ctrl_28_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_PHS_ctrl_28_0 || ORIG_REF_NAME==S7_PHS_ctrl_28_0} -quiet] -quiet

# IP: bd/S7/ip/S7_PHS_ctrl_29_0/S7_PHS_ctrl_29_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_PHS_ctrl_29_0 || ORIG_REF_NAME==S7_PHS_ctrl_29_0} -quiet] -quiet

# IP: bd/S7/ip/S7_PHS_ctrl_30_0/S7_PHS_ctrl_30_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_PHS_ctrl_30_0 || ORIG_REF_NAME==S7_PHS_ctrl_30_0} -quiet] -quiet

# IP: bd/S7/ip/S7_PHS_ctrl_31_0/S7_PHS_ctrl_31_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_PHS_ctrl_31_0 || ORIG_REF_NAME==S7_PHS_ctrl_31_0} -quiet] -quiet

# IP: bd/S7/ip/S7_PHS_ctrl_32_0/S7_PHS_ctrl_32_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_PHS_ctrl_32_0 || ORIG_REF_NAME==S7_PHS_ctrl_32_0} -quiet] -quiet

# IP: bd/S7/ip/S7_PHS_ctrl_33_0/S7_PHS_ctrl_33_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_PHS_ctrl_33_0 || ORIG_REF_NAME==S7_PHS_ctrl_33_0} -quiet] -quiet

# IP: bd/S7/ip/S7_PHS_ctrl_34_0/S7_PHS_ctrl_34_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_PHS_ctrl_34_0 || ORIG_REF_NAME==S7_PHS_ctrl_34_0} -quiet] -quiet

# IP: bd/S7/ip/S7_PHS_ctrl_35_0/S7_PHS_ctrl_35_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_PHS_ctrl_35_0 || ORIG_REF_NAME==S7_PHS_ctrl_35_0} -quiet] -quiet

# IP: bd/S7/ip/S7_PHS_ctrl_36_0/S7_PHS_ctrl_36_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_PHS_ctrl_36_0 || ORIG_REF_NAME==S7_PHS_ctrl_36_0} -quiet] -quiet

# IP: bd/S7/ip/S7_PHS_ctrl_37_0/S7_PHS_ctrl_37_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_PHS_ctrl_37_0 || ORIG_REF_NAME==S7_PHS_ctrl_37_0} -quiet] -quiet

# IP: bd/S7/ip/S7_PHS_ctrl_38_0/S7_PHS_ctrl_38_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_PHS_ctrl_38_0 || ORIG_REF_NAME==S7_PHS_ctrl_38_0} -quiet] -quiet

# IP: bd/S7/ip/S7_PHS_ctrl_39_0/S7_PHS_ctrl_39_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_PHS_ctrl_39_0 || ORIG_REF_NAME==S7_PHS_ctrl_39_0} -quiet] -quiet

# IP: bd/S7/ip/S7_PHS_ctrl_40_0/S7_PHS_ctrl_40_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_PHS_ctrl_40_0 || ORIG_REF_NAME==S7_PHS_ctrl_40_0} -quiet] -quiet

# IP: bd/S7/ip/S7_PHS_ctrl_41_0/S7_PHS_ctrl_41_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_PHS_ctrl_41_0 || ORIG_REF_NAME==S7_PHS_ctrl_41_0} -quiet] -quiet

# IP: bd/S7/ip/S7_PHS_ctrl_42_0/S7_PHS_ctrl_42_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_PHS_ctrl_42_0 || ORIG_REF_NAME==S7_PHS_ctrl_42_0} -quiet] -quiet

# IP: bd/S7/ip/S7_PHS_ctrl_43_0/S7_PHS_ctrl_43_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_PHS_ctrl_43_0 || ORIG_REF_NAME==S7_PHS_ctrl_43_0} -quiet] -quiet

# IP: bd/S7/ip/S7_PHS_ctrl_44_0/S7_PHS_ctrl_44_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_PHS_ctrl_44_0 || ORIG_REF_NAME==S7_PHS_ctrl_44_0} -quiet] -quiet

# IP: bd/S7/ip/S7_PHS_ctrl_45_0/S7_PHS_ctrl_45_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_PHS_ctrl_45_0 || ORIG_REF_NAME==S7_PHS_ctrl_45_0} -quiet] -quiet

# IP: bd/S7/ip/S7_PHS_ctrl_46_0/S7_PHS_ctrl_46_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_PHS_ctrl_46_0 || ORIG_REF_NAME==S7_PHS_ctrl_46_0} -quiet] -quiet

# IP: bd/S7/ip/S7_PHS_ctrl_47_0/S7_PHS_ctrl_47_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_PHS_ctrl_47_0 || ORIG_REF_NAME==S7_PHS_ctrl_47_0} -quiet] -quiet

# IP: bd/S7/ip/S7_PHS_ctrl_48_0/S7_PHS_ctrl_48_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_PHS_ctrl_48_0 || ORIG_REF_NAME==S7_PHS_ctrl_48_0} -quiet] -quiet

# IP: bd/S7/ip/S7_PHS_ctrl_49_0/S7_PHS_ctrl_49_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_PHS_ctrl_49_0 || ORIG_REF_NAME==S7_PHS_ctrl_49_0} -quiet] -quiet

# IP: bd/S7/ip/S7_PHS_regs_0_0/S7_PHS_regs_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_PHS_regs_0_0 || ORIG_REF_NAME==S7_PHS_regs_0_0} -quiet] -quiet

# IP: bd/S7/ip/S7_RT_timebase_0_0/S7_RT_timebase_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_RT_timebase_0_0 || ORIG_REF_NAME==S7_RT_timebase_0_0} -quiet] -quiet

# IP: bd/S7/ip/S7_SM_alg_server_0_0/S7_SM_alg_server_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_SM_alg_server_0_0 || ORIG_REF_NAME==S7_SM_alg_server_0_0} -quiet] -quiet

# IP: bd/S7/ip/S7_SM_alg_server_1_0/S7_SM_alg_server_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_SM_alg_server_1_0 || ORIG_REF_NAME==S7_SM_alg_server_1_0} -quiet] -quiet

# IP: bd/S7/ip/S7_SM_ctrl_0_0/S7_SM_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_SM_ctrl_0_0 || ORIG_REF_NAME==S7_SM_ctrl_0_0} -quiet] -quiet

# IP: bd/S7/ip/S7_SM_ctrl_1_0/S7_SM_ctrl_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_SM_ctrl_1_0 || ORIG_REF_NAME==S7_SM_ctrl_1_0} -quiet] -quiet

# IP: bd/S7/ip/S7_SM_ctrl_2_0/S7_SM_ctrl_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_SM_ctrl_2_0 || ORIG_REF_NAME==S7_SM_ctrl_2_0} -quiet] -quiet

# IP: bd/S7/ip/S7_SM_ctrl_3_0/S7_SM_ctrl_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_SM_ctrl_3_0 || ORIG_REF_NAME==S7_SM_ctrl_3_0} -quiet] -quiet

# IP: bd/S7/ip/S7_SM_ctrl_4_0/S7_SM_ctrl_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_SM_ctrl_4_0 || ORIG_REF_NAME==S7_SM_ctrl_4_0} -quiet] -quiet

# IP: bd/S7/ip/S7_SM_ctrl_5_0/S7_SM_ctrl_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_SM_ctrl_5_0 || ORIG_REF_NAME==S7_SM_ctrl_5_0} -quiet] -quiet

# IP: bd/S7/ip/S7_SM_ctrl_6_0/S7_SM_ctrl_6_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_SM_ctrl_6_0 || ORIG_REF_NAME==S7_SM_ctrl_6_0} -quiet] -quiet

# IP: bd/S7/ip/S7_SM_ctrl_7_0/S7_SM_ctrl_7_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_SM_ctrl_7_0 || ORIG_REF_NAME==S7_SM_ctrl_7_0} -quiet] -quiet

# IP: bd/S7/ip/S7_SM_ctrl_8_0/S7_SM_ctrl_8_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_SM_ctrl_8_0 || ORIG_REF_NAME==S7_SM_ctrl_8_0} -quiet] -quiet

# IP: bd/S7/ip/S7_SM_ctrl_9_0/S7_SM_ctrl_9_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_SM_ctrl_9_0 || ORIG_REF_NAME==S7_SM_ctrl_9_0} -quiet] -quiet

# IP: bd/S7/ip/S7_SM_ctrl_10_0/S7_SM_ctrl_10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_SM_ctrl_10_0 || ORIG_REF_NAME==S7_SM_ctrl_10_0} -quiet] -quiet

# IP: bd/S7/ip/S7_SM_ctrl_11_0/S7_SM_ctrl_11_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_SM_ctrl_11_0 || ORIG_REF_NAME==S7_SM_ctrl_11_0} -quiet] -quiet

# IP: bd/S7/ip/S7_SM_ctrl_12_0/S7_SM_ctrl_12_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_SM_ctrl_12_0 || ORIG_REF_NAME==S7_SM_ctrl_12_0} -quiet] -quiet

# IP: bd/S7/ip/S7_SM_ctrl_13_0/S7_SM_ctrl_13_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_SM_ctrl_13_0 || ORIG_REF_NAME==S7_SM_ctrl_13_0} -quiet] -quiet

# IP: bd/S7/ip/S7_SM_ctrl_14_0/S7_SM_ctrl_14_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_SM_ctrl_14_0 || ORIG_REF_NAME==S7_SM_ctrl_14_0} -quiet] -quiet

# IP: bd/S7/ip/S7_SM_ctrl_15_0/S7_SM_ctrl_15_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_SM_ctrl_15_0 || ORIG_REF_NAME==S7_SM_ctrl_15_0} -quiet] -quiet

# IP: bd/S7/ip/S7_SM_ctrl_16_0/S7_SM_ctrl_16_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_SM_ctrl_16_0 || ORIG_REF_NAME==S7_SM_ctrl_16_0} -quiet] -quiet

# IP: bd/S7/ip/S7_SM_ctrl_17_0/S7_SM_ctrl_17_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_SM_ctrl_17_0 || ORIG_REF_NAME==S7_SM_ctrl_17_0} -quiet] -quiet

# IP: bd/S7/ip/S7_SM_ctrl_18_0/S7_SM_ctrl_18_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_SM_ctrl_18_0 || ORIG_REF_NAME==S7_SM_ctrl_18_0} -quiet] -quiet

# IP: bd/S7/ip/S7_SM_ctrl_19_0/S7_SM_ctrl_19_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_SM_ctrl_19_0 || ORIG_REF_NAME==S7_SM_ctrl_19_0} -quiet] -quiet

# IP: bd/S7/ip/S7_SM_regs_0_0/S7_SM_regs_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_SM_regs_0_0 || ORIG_REF_NAME==S7_SM_regs_0_0} -quiet] -quiet

# IP: bd/S7/ip/S7_SOL_ctrl_0_0/S7_SOL_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_SOL_ctrl_0_0 || ORIG_REF_NAME==S7_SOL_ctrl_0_0} -quiet] -quiet

# IP: bd/S7/ip/S7_SOL_ctrl_1_0/S7_SOL_ctrl_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_SOL_ctrl_1_0 || ORIG_REF_NAME==S7_SOL_ctrl_1_0} -quiet] -quiet

# IP: bd/S7/ip/S7_SOL_ctrl_2_0/S7_SOL_ctrl_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_SOL_ctrl_2_0 || ORIG_REF_NAME==S7_SOL_ctrl_2_0} -quiet] -quiet

# IP: bd/S7/ip/S7_SOL_ctrl_3_0/S7_SOL_ctrl_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_SOL_ctrl_3_0 || ORIG_REF_NAME==S7_SOL_ctrl_3_0} -quiet] -quiet

# IP: bd/S7/ip/S7_SOL_ctrl_4_0/S7_SOL_ctrl_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_SOL_ctrl_4_0 || ORIG_REF_NAME==S7_SOL_ctrl_4_0} -quiet] -quiet

# IP: bd/S7/ip/S7_SOL_ctrl_5_0/S7_SOL_ctrl_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_SOL_ctrl_5_0 || ORIG_REF_NAME==S7_SOL_ctrl_5_0} -quiet] -quiet

# IP: bd/S7/ip/S7_SOL_ctrl_6_0/S7_SOL_ctrl_6_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_SOL_ctrl_6_0 || ORIG_REF_NAME==S7_SOL_ctrl_6_0} -quiet] -quiet

# IP: bd/S7/ip/S7_SOL_ctrl_7_0/S7_SOL_ctrl_7_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_SOL_ctrl_7_0 || ORIG_REF_NAME==S7_SOL_ctrl_7_0} -quiet] -quiet

# IP: bd/S7/ip/S7_SOL_ctrl_8_0/S7_SOL_ctrl_8_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_SOL_ctrl_8_0 || ORIG_REF_NAME==S7_SOL_ctrl_8_0} -quiet] -quiet

# IP: bd/S7/ip/S7_SOL_ctrl_9_0/S7_SOL_ctrl_9_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_SOL_ctrl_9_0 || ORIG_REF_NAME==S7_SOL_ctrl_9_0} -quiet] -quiet

# IP: bd/S7/ip/S7_SOL_regs_0_0/S7_SOL_regs_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_SOL_regs_0_0 || ORIG_REF_NAME==S7_SOL_regs_0_0} -quiet] -quiet

# IP: bd/S7/ip/S7_axi_gpio_0_0/S7_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_axi_gpio_0_0 || ORIG_REF_NAME==S7_axi_gpio_0_0} -quiet] -quiet

# IP: bd/S7/ip/S7_axi_uartlite_0_0/S7_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_axi_uartlite_0_0 || ORIG_REF_NAME==S7_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/S7/ip/S7_clk_wiz_1_0/S7_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_clk_wiz_1_0 || ORIG_REF_NAME==S7_clk_wiz_1_0} -quiet] -quiet

# IP: bd/S7/ip/S7_mdm_1_0/S7_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_mdm_1_0 || ORIG_REF_NAME==S7_mdm_1_0} -quiet] -quiet

# IP: bd/S7/ip/S7_microblaze_0_0/S7_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_microblaze_0_0 || ORIG_REF_NAME==S7_microblaze_0_0} -quiet] -quiet

# IP: bd/S7/ip/S7_microblaze_0_axi_periph_0/S7_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_microblaze_0_axi_periph_0 || ORIG_REF_NAME==S7_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/S7/ip/S7_dlmb_bram_if_cntlr_0/S7_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==S7_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/S7/ip/S7_dlmb_v10_0/S7_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_dlmb_v10_0 || ORIG_REF_NAME==S7_dlmb_v10_0} -quiet] -quiet

# IP: bd/S7/ip/S7_ilmb_bram_if_cntlr_0/S7_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==S7_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/S7/ip/S7_ilmb_v10_0/S7_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_ilmb_v10_0 || ORIG_REF_NAME==S7_ilmb_v10_0} -quiet] -quiet

# IP: bd/S7/ip/S7_lmb_bram_0/S7_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_lmb_bram_0 || ORIG_REF_NAME==S7_lmb_bram_0} -quiet] -quiet

# IP: bd/S7/ip/S7_rst_clk_wiz_1_100M_0/S7_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==S7_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/S7/ip/S7_axi_chip2chip_0_0/S7_axi_chip2chip_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_axi_chip2chip_0_0 || ORIG_REF_NAME==S7_axi_chip2chip_0_0} -quiet] -quiet

# IP: bd/S7/ip/S7_util_ds_buf_0_0/S7_util_ds_buf_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_util_ds_buf_0_0 || ORIG_REF_NAME==S7_util_ds_buf_0_0} -quiet] -quiet

# IP: bd/S7/ip/S7_axi_bram_ctrl_0_0/S7_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_axi_bram_ctrl_0_0 || ORIG_REF_NAME==S7_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/S7/ip/S7_blk_mem_gen_0_0/S7_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_blk_mem_gen_0_0 || ORIG_REF_NAME==S7_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/S7/ip/S7_areset_sync_0_0/S7_areset_sync_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_areset_sync_0_0 || ORIG_REF_NAME==S7_areset_sync_0_0} -quiet] -quiet

# IP: bd/S7/ip/S7_util_ds_buf_0_1/S7_util_ds_buf_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_util_ds_buf_0_1 || ORIG_REF_NAME==S7_util_ds_buf_0_1} -quiet] -quiet

# IP: bd/S7/ip/S7_util_idelay_ctrl_0_0/S7_util_idelay_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_util_idelay_ctrl_0_0 || ORIG_REF_NAME==S7_util_idelay_ctrl_0_0} -quiet] -quiet

# IP: bd/S7/ip/S7_axi_cdma_0_0/S7_axi_cdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_axi_cdma_0_0 || ORIG_REF_NAME==S7_axi_cdma_0_0} -quiet] -quiet

# IP: bd/S7/ip/S7_axi_interconnect_0_0/S7_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_axi_interconnect_0_0 || ORIG_REF_NAME==S7_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/S7/ip/S7_xbar_1/S7_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_xbar_1 || ORIG_REF_NAME==S7_xbar_1} -quiet] -quiet

# IP: bd/S7/ip/S7_xbar_2/S7_xbar_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_xbar_2 || ORIG_REF_NAME==S7_xbar_2} -quiet] -quiet

# IP: bd/S7/ip/S7_xlconcat_0_0/S7_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_xlconcat_0_0 || ORIG_REF_NAME==S7_xlconcat_0_0} -quiet] -quiet

# IP: bd/S7/ip/S7_axi_intc_0_0/S7_axi_intc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_axi_intc_0_0 || ORIG_REF_NAME==S7_axi_intc_0_0} -quiet] -quiet

# IP: bd/S7/ip/S7_xlconcat_0_1/S7_xlconcat_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_xlconcat_0_1 || ORIG_REF_NAME==S7_xlconcat_0_1} -quiet] -quiet

# IP: bd/S7/ip/S7_xlconstant_0_0/S7_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_xlconstant_0_0 || ORIG_REF_NAME==S7_xlconstant_0_0} -quiet] -quiet

# IP: bd/S7/ip/S7_SM_alg_server_0_0_1/S7_SM_alg_server_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_SM_alg_server_0_0 || ORIG_REF_NAME==S7_SM_alg_server_0_0} -quiet] -quiet

# IP: bd/S7/ip/S7_SM_alg_server_1_0_1/S7_SM_alg_server_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_SM_alg_server_1_0 || ORIG_REF_NAME==S7_SM_alg_server_1_0} -quiet] -quiet

# IP: bd/S7/ip/S7_auto_pc_0/S7_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S7_auto_pc_0 || ORIG_REF_NAME==S7_auto_pc_0} -quiet] -quiet

# XDC: bd/S7/S7_ooc.xdc
