@echo off
REM ****************************************************************************
REM Vivado (TM) v2018.3_AR72013 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue Apr 14 11:19:31 +0200 2020
REM SW Build 2405991 on Thu Dec  6 23:38:27 MST 2018
REM
REM Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
call xsim SOL_ctrl_TB_behav -key {Behavioral:sim_1:Functional:SOL_ctrl_TB} -tclbatch SOL_ctrl_TB.tcl -view D:/MW/RTT/VVD/ZED/P0/repo/SOL_ctrl/SOL_ctrl_TB_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
